apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "domain-exporter.fullname" . }}-domains
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "domain-exporter.labels" . | nindent 4 }}
data:
  domains.yaml: |-
    domains:
    {{- range .Values.domains }}
      - {{ . }}
    {{- end }}
