image:
  registry: ""
  repository: yandex/clickhouse-server
  tag: ""
  pullPolicy: Always

clusterName: my-cluster

defaults:
  templates:
    podTemplate: default
    dataVolumeClaimTemplate: default
    # specify  template: service-template or service-template-node-port
    serviceTemplate: service-template

configuration:
  users: {}

  profiles:
    default/max_query_size: 41943040
    default/max_ast_elements: 100000

  clusters:
  - name: test
    layout:
      replicasCount: 1
      shardsCount: 1

  zookeeper:
    nodes:
      - host: zookeeper
        port: 2181

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  requests:
#    cpu: 250m
#    memory: 256Mi
#  limits:
#    cpu: 250m
#    memory: 256Mi

nodeSelector: {}

storage:
  storageClassName: ""
  size: 500Mi
