apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "clickhouse-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
