{{ if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clickhouse-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "clickhouse-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.metrics.interval }}
{{ end }}
