architecture: standalone
auth:
  enabled: false

cluster:
  enabled: false

master:
  persistence:
    enabled: false

  resources:
    requests:
      cpu: "100m"
      memory: "150Mi"
    limits:
      memory: "150Mi"

replica:
  persistence:
    enabled: false

  resources:
    requests:
      cpu: "100m"
      memory: "150Mi"
    limits:
      memory: "150Mi"
