dashboards:
  targetFolder: "kafka"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: "/clickhouse-exporter(/|$)(.*)"
          pathType: Prefix

clickhouse:
  - name: cluster
    user: my_user
    password: my_pass
    hosts:
     - chi-clickhouse-my-cluster-my-cluster-0-0.clickhouse.svc
     - chi-clickhouse-my-cluster-my-cluster-0-1.clickhouse.svc
