dashboards:
  targetFolder: "kafka"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: "/kafka-exporter(/|$)(.*)"
          pathType: Prefix

kafka:
  - name: test-cluster
    brokers:
      - kafka.test.svc.cluster.local:9092
  - name: test-cluster-sasl
    user: kafka_user
    password: kafka_pass
    mechanism: plain
    brokers:
      - kafka-sasl.test.svc.cluster.local:9092
