dashboards:
  targetFolder: "zookeeper"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: "/zookeeper-exporter(/|$)(.*)"
          pathType: Prefix

zookeeper:
  - name: cluster1
    hosts:
      - zookeeper.test.svc:2181
