apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: {{ default .Release.Name .Values.name }}
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ required "A valid .Values.tls.crt is required!" .Values.tls.crt | b64enc | quote }}
  tls.key: {{ required "A valid .Values.tls.key is required!" .Values.tls.key | b64enc | quote }}
