name: Run Helm Test Cases
on: pull_request
jobs:
  Helm-Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Tests
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |-
            helm plugin install https://github.com/quintush/helm-unittest &&
            /github/workspace/dev/run-tests.sh

  Helm-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --debug
#
#      - name: Create kind cluster
#        uses: helm/kind-action@v1.2.0
#        if: steps.list-changed.outputs.changed == 'true'
#
#      - name: Run chart-testing (install)
#        run: ct install